/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualRouteImport } from './routes/visual'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const VisualRoute = VisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/docs': typeof DocsRoute
  '/incidents': typeof IncidentsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/visual': typeof VisualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/docs': typeof DocsRoute
  '/incidents': typeof IncidentsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/visual': typeof VisualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/docs': typeof DocsRoute
  '/incidents': typeof IncidentsRoute
  '/memory': typeof MemoryRoute
  '/projects': typeof ProjectsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/visual': typeof VisualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/docs'
    | '/incidents'
    | '/memory'
    | '/projects'
    | '/tasks'
    | '/team'
    | '/visual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/docs'
    | '/incidents'
    | '/memory'
    | '/projects'
    | '/tasks'
    | '/team'
    | '/visual'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/docs'
    | '/incidents'
    | '/memory'
    | '/projects'
    | '/tasks'
    | '/team'
    | '/visual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DocsRoute: typeof DocsRoute
  IncidentsRoute: typeof IncidentsRoute
  MemoryRoute: typeof MemoryRoute
  ProjectsRoute: typeof ProjectsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  VisualRoute: typeof VisualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual': {
      id: '/visual'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof VisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DocsRoute: DocsRoute,
  IncidentsRoute: IncidentsRoute,
  MemoryRoute: MemoryRoute,
  ProjectsRoute: ProjectsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  VisualRoute: VisualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
